site_name: openITCOCKPIT 4
site_url: http://mkdocs.oitc.itn:8000/en/
repo_url: https://github.com/it-novum/openITCOCKPIT-documentation
repo_name: GitHub
edit_uri: https://github.com/it-novum/openITCOCKPIT-documentation/blob/main/en/docs/
dev_addr: 0.0.0.0:8000

nav:
  - 'About openITCOCKPIT': 'index.md'

extra_javascript:
  - vendor/jquery-3.6.0.min.js
  - vendor/featherlight-v.1.7.14/release/featherlight.min.js
  - copyright_year.js

markdown_extensions:
    - toc:
        permalink: True
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - attr_list
    - def_list
    - markdown_include.include:
          base_path: docs
    - admonition
    - featherlight

extra_css:
  - bootstrap-selection.css
  - vendor/font-awesome-4.7.0/css/font-awesome.min.css
  - vendor/featherlight-v.1.7.14/release/featherlight.min.css
  - oitc.css

plugins:
  - search

#  Theme docs: https://squidfunk.github.io/mkdocs-material/getting-started/
theme:
  name: material
  language: de
  logo: images/logo/openitcockpit-light.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: blue
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode



copyright: Copyright &copy; 2016 - <span id="copyright-year">YYYY</span> it-novum GmbH

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openITCOCKPIT
    - icon: fontawesome/brands/discord
      link: https://discord.gg/G8KhxKuQ9G
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/openitcockpit/
    - icon: fontawesome/brands/github
      link: https://github.com/it-novum/openITCOCKPIT
  alternate:
    - link: /
      name: de - Deutsch
      lang: de
    - link: /en/
      name: en - English
      lang: en

