site_name: openITCOCKPIT 4
site_url: http://mkdocs.oitc.itn:8000/
repo_url: https://github.com/it-novum/openITCOCKPIT-documentation
repo_name: GitHub
dev_addr: 0.0.0.0:8000

nav:
  - 'Über openITCOCKPIT': 'index.md'
  - 'Installation': 'installation.md'
  - 'Beginners Guide': 'beginners.md'
  - 'Monitoring':
    - 'Grundlegende Prinzipien': 'monitoring/basic-priciples.md'
    - 'User Interface': 'monitoring/user-interface.md'
    - 'Dashboard': 'monitoring/dashboard.md'
    - 'Acknowledging' : 'monitoring/acknowledging.md'
    - 'Downtimes': 'monitoring/downtimes.md'
    - 'Graphing': 'monitoring/graphing.md'
    - 'Überwachung mit Prometheus': 'monitoring/prometheus.md'
    - 'Überwachung mit Checkmk': 'monitoring/checkmk.md'
    - 'Karten': 'monitoring/maps.md'
    - 'Eventkorrelation': 'monitoring/eventcorrelation.md'
  - 'Alerting / Benachrichtigungen': 'alerting.md'
  - 'Reporting': 'reporting.md'
  - 'Konfiguration': 
    - 'Container': 'configuration/container.md'
    - 'Host und Services': 'configuration/host-services.md'
    - 'Benutzerverwaltung': 'configuration/usermanagement.md'
    - 'Makros': 'configuration/macros.md'
    - 'Zeitabschnitte' : 'configuration/timeperiods.md'
    - 'Kalender': 'configuration/calendar.md'
    - 'Cronjobs': 'configuration/cronjobs.md'
    - 'Paketmanager': 'configuration/packagemanager.md'
    - 'Backup & Restore': 'configuration/backup-restore.md'
    - 'Konfigurationsdateien': 'configuration/config-file-editor.md'
    - 'Proxy': 'configuration/proxy.md'
    - 'Verteiltes Monitoring und Satelliten': 'configuration/distribute-module.md'
    - 'SNMP Traps': 'configuration/snmp-trap-module.md'
  - 'Development':
    - 'Entwicklungsumgebung einrichten': 'development/setup-dev-env.md'
  - 'Weitere Artikel':
    - 'Logging': 'additional/logs.md'
    - 'Theming und CI': 'additional/theming.md'
    - 'Troubleshooting': 'additional/troubleshooting.md'

extra_javascript:
  - copyright_year.js
markdown_extensions:
    - toc:
        permalink: True
    - pymdownx.highlight
    - pymdownx.superfences
    - attr_list
    - def_list
    - markdown_include.include:
          base_path: docs

plugins:
  - search

#  Theme docs: https://squidfunk.github.io/mkdocs-material/getting-started/
theme:
  name: material
  language: de
  logo: images/logo/openitcockpit-light.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: blue
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.expand


copyright: Copyright &copy; 2016 - <span id="copyright-year">YYYY</span> it-novum GmbH

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openITCOCKPIT
    - icon: fontawesome/brands/discord
      link: https://discord.gg/G8KhxKuQ9G
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/openitcockpit/
    - icon: fontawesome/brands/github
      link: https://github.com/it-novum/openITCOCKPIT
  alternate:
    - link: /
      name: de - Deutsch
      lang: de
    - link: /en/
      name: en - English
      lang: en